In [122]:
import pandas as pd

df=pd.read_csv("https://raw.githubusercontent.com/su-mt4007/data/refs/heads/main/Booli_sold.csv")

# Apartment Prices

### Task 1

Calculate ppsqm and add as a varible to the table.

In [123]:
df['ppsq'] = round(df['soldPrice']/df['livingArea'])
df

,listPrice,rent,livingArea,rooms,published,constructionYear,objectType,booliId,soldDate,soldPrice,...,location.position.longitude,location.position.isApproximate,location.region.municipalityName,location.region.countyName,location.distance.ocean,source.name,source.id,source.type,source.url,ppsq
0,3995000,4467.0,73.0,3.0,2018-10-15 13:33:18,1935.0,Lägenhet,3263989,2018-11-08,3820000,...,18.054057,NaN,Stockholm,Stockholms län,260,MOHV,1901865,Broker,http://www.mohv.se/,52329.0
1,1995000,1773.0,36.0,1.0,2018-10-05 14:29:28,1968.0,Lägenhet,3256231,2018-10-19,2355000,...,18.057821,NaN,Stockholm,Stockholms län,218,Notar,1566,Broker,http://www.notar.se/,65417.0
2,5100000,3839.0,81.0,3.0,2018-09-11 13:44:43,1936.0,Lägenhet,3236660,2018-09-27,6110000,...,18.054716,NaN,Stockholm,Stockholms län,186,Historiska Hem AB,65645750,Broker,http://historiskahem.se/,75432.0
3,5495000,4483.0,107.0,4.0,2018-08-25 02:56:56,1936.0,Lägenhet,3224374,2018-09-06,8050000,...,18.053880,NaN,Stockholm,Stockholms län,218,Notar,1566,Broker,http://www.notar.se/,75234.0
4,1995000,1696.0,29.0,1.0,2018-06-15 17:16:19,1936.0,Lägenhet,3185496,2018-06-18,2400000,...,18.053542,True,Stockholm,Stockholms län,166,Mäklarhuset,204,Broker,http://www.maklarhuset.se/,82759.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,1495000,1388.0,26.0,1.0,2012-10-20 07:36:37,1935.0,Lägenhet,1297784,2012-11-30,1475000,...,18.055659,True,Stockholm,Stockholms län,101,Notar,1566,Broker,http://www.notar.se/,56731.0
154,2245000,2455.0,50.0,2.0,2012-10-19 15:32:58,1935.0,Lägenhet,1296874,2012-10-27,2245000,...,18.055659,True,Stockholm,Stockholms län,101,Notar,1566,Broker,http://www.notar.se/,44900.0
155,1450000,1072.0,23.0,1.0,2012-09-14 05:10:08,1936.0,Lägenhet,1270599,2012-10-22,1450000,...,18.053552,NaN,Stockholm,Stockholms län,255,Notar,1566,Broker,http://www.notar.se/,63043.0
156,2495000,2748.0,56.0,3.0,2012-09-21 12:19:37,1935.0,Lägenhet,1276232,2012-10-09,2200000,...,18.054634,True,Stockholm,Stockholms län,70,Notar,1566,Broker,http://www.notar.se/,39286.0
157,2300000,2455.0,50.0,2.0,2012-09-16 02:33:35,1935.0,Lägenhet,1272477,2012-10-09,2180000,...,18.055659,True,Stockholm,Stockholms län,101,Notar,1566,Broker,http://www.notar.se/,43600.0

### Task 2

Rank the top 5 most expensive appartments wrt ppsqm.

In [124]:
df_top5 = df.sort_values(by='ppsq', ascending=False)
df_top5 = df_top5[:5]
df_top5

,listPrice,rent,livingArea,rooms,published,constructionYear,objectType,booliId,soldDate,soldPrice,...,location.position.longitude,location.position.isApproximate,location.region.municipalityName,location.region.countyName,location.distance.ocean,source.name,source.id,source.type,source.url,ppsq
67,1595000,1464.0,24.0,1.0,2016-01-07 14:51:06,1935.0,Lägenhet,2018259,2016-01-21,2500000,...,18.055270,NaN,Stockholm,Stockholms län,161,Notar,1566,Broker,http://www.notar.se/,104167.0
50,1890000,1464.0,24.0,1.0,2016-06-11 08:55:51,1935.0,Lägenhet,2125576,2016-06-21,2450000,...,18.055270,NaN,Stockholm,Stockholms län,161,HusmanHagberg,1610,Broker,http://www.husmanhagberg.se/,102083.0
54,1795000,1374.0,23.0,1.0,2016-04-15 19:10:49,1935.0,Lägenhet,2078171,2016-04-28,2300000,...,18.055422,True,Stockholm,Stockholms län,135,Notar,1566,Broker,http://www.notar.se/,100000.0
34,1750000,1144.0,25.0,1.0,2017-05-18 16:20:57,1936.0,Lägenhet,2330886,2017-06-01,2210000,...,18.053880,NaN,Stockholm,Stockholms län,218,HusmanHagberg,1610,Broker,http://www.husmanhagberg.se/,88400.0
55,1895000,1522.0,26.9,1.0,2016-04-01 22:56:37,1968.0,Lägenhet,2067384,2016-04-19,2300000,...,18.058529,True,Stockholm,Stockholms län,298,Notar,1566,Broker,http://www.notar.se/,85502.0

### Task 3

Average ppsqm in Ekhagen.

In [125]:
ppsq = df['ppsq']

ppsq_avg = ppsq.mean()

ppsq_avg = f"{ppsq_avg:.0f}"
ppsq_avg

'58759'

### Task 4 

I will add a new column with the % change from list price to sold price. It is a common varible to use in the context of the housing market.

In [126]:
df['% Change list vs sold'] = df['soldPrice']/df['listPrice']
df['% Change list vs sold'] = (df['% Change list vs sold']-1) * 100
df['% Change list vs sold'] = df['% Change list vs sold'].map("{:.2f}%".format)
df

,listPrice,rent,livingArea,rooms,published,constructionYear,objectType,booliId,soldDate,soldPrice,...,location.position.isApproximate,location.region.municipalityName,location.region.countyName,location.distance.ocean,source.name,source.id,source.type,source.url,ppsq,% Change list vs sold
0,3995000,4467.0,73.0,3.0,2018-10-15 13:33:18,1935.0,Lägenhet,3263989,2018-11-08,3820000,...,NaN,Stockholm,Stockholms län,260,MOHV,1901865,Broker,http://www.mohv.se/,52329.0,-4.38%
1,1995000,1773.0,36.0,1.0,2018-10-05 14:29:28,1968.0,Lägenhet,3256231,2018-10-19,2355000,...,NaN,Stockholm,Stockholms län,218,Notar,1566,Broker,http://www.notar.se/,65417.0,18.05%
2,5100000,3839.0,81.0,3.0,2018-09-11 13:44:43,1936.0,Lägenhet,3236660,2018-09-27,6110000,...,NaN,Stockholm,Stockholms län,186,Historiska Hem AB,65645750,Broker,http://historiskahem.se/,75432.0,19.80%
3,5495000,4483.0,107.0,4.0,2018-08-25 02:56:56,1936.0,Lägenhet,3224374,2018-09-06,8050000,...,NaN,Stockholm,Stockholms län,218,Notar,1566,Broker,http://www.notar.se/,75234.0,46.50%
4,1995000,1696.0,29.0,1.0,2018-06-15 17:16:19,1936.0,Lägenhet,3185496,2018-06-18,2400000,...,True,Stockholm,Stockholms län,166,Mäklarhuset,204,Broker,http://www.maklarhuset.se/,82759.0,20.30%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,1495000,1388.0,26.0,1.0,2012-10-20 07:36:37,1935.0,Lägenhet,1297784,2012-11-30,1475000,...,True,Stockholm,Stockholms län,101,Notar,1566,Broker,http://www.notar.se/,56731.0,-1.34%
154,2245000,2455.0,50.0,2.0,2012-10-19 15:32:58,1935.0,Lägenhet,1296874,2012-10-27,2245000,...,True,Stockholm,Stockholms län,101,Notar,1566,Broker,http://www.notar.se/,44900.0,0.00%
155,1450000,1072.0,23.0,1.0,2012-09-14 05:10:08,1936.0,Lägenhet,1270599,2012-10-22,1450000,...,NaN,Stockholm,Stockholms län,255,Notar,1566,Broker,http://www.notar.se/,63043.0,0.00%
156,2495000,2748.0,56.0,3.0,2012-09-21 12:19:37,1935.0,Lägenhet,1276232,2012-10-09,2200000,...,True,Stockholm,Stockholms län,70,Notar,1566,Broker,http://www.notar.se/,39286.0,-11.82%
157,2300000,2455.0,50.0,2.0,2012-09-16 02:33:35,1935.0,Lägenhet,1272477,2012-10-09,2180000,...,True,Stockholm,Stockholms län,101,Notar,1566,Broker,http://www.notar.se/,43600.0,-5.22%

# The Swedish Election of 2018

### Task 1

Sum the legitimate votes for all municipalities in Stockholm.

In [127]:
df_2 = df=pd.read_csv("https://raw.githubusercontent.com/su-mt4007/data/refs/heads/main/2018_R_per_kommun.csv", delimiter=';')

votes_sthlm = df.loc[df['LÄNSNAMN']=='Stockholms län', 'RÖSTER GILTIGA'].sum()
votes_sthlm = int(votes_sthlm)
votes_sthlm

1426237

### Task 2

In which municipality did the social democratic party (Social demokraterna, S) garner the hightest voting percentage?

In [128]:
df_2['S'] = df_2['S'].str.replace(',', '.').astype(float)

df_2_s = df_2.sort_values(by='S', ascending=False)

kommun = df_2_s['KOMMUNNAMN'].iloc[0]
kommun

'Munkfors'

### Task 3

Rank the three highest municipialities wrt participation in the election

In [129]:
df_2['VALDELTAGANDE'] = df_2['VALDELTAGANDE'].str.replace(',', '.').astype(float)

df_2_p = df_2.sort_values(by='VALDELTAGANDE', ascending=False)

df_2_p[:5]

,LÄNSKOD,KOMMUNKOD,LÄNSNAMN,KOMMUNNAMN,M,C,L,KD,S,V,...,TRP,VL-S,ÖVR,OGEJ,BLANK,OG,RÖSTER GILTIGA,RÖSTANDE,RÖSTBERÄTTIGADE,VALDELTAGANDE
103,12,62,Skåne län,Lomma,"33,16","9,33","9,97","6,38",16.69,"2,54",...,NaN,NaN,NaN,NaN,"0,51","0,04",16401,16492,17570,93.86
59,6,43,Jönköpings län,Habo,"19,73","8,77","4,22","15,13",23.74,"3,91",...,NaN,NaN,NaN,"0,06","0,88","0,06",7746,7825,8382,93.35
98,12,33,Skåne län,Vellinge,"39,56","7,24","7,26","7,45",10.58,"1,31",...,0,NaN,NaN,"0,02","0,4","0,04",25245,25360,27231,93.13
22,1,87,Stockholms län,Vaxholm,"30,31","13,3","7,76","7,9",16.37,"4,7",...,NaN,NaN,"0,01","0,04","0,48","0,06",8106,8153,8791,92.74
5,1,25,Stockholms län,Ekerö,"28,12","11,24","7,64","7,85",17.17,"4,76",...,NaN,NaN,"0,01","0,01","0,64","0,08",17814,17946,19472,92.16